# 下载器基础配置
default:
  # 最大工作线程数（1-10）
  max_workers: 5
  
  # 默认下载路径（支持环境变量）
  download_path: ${HOME}/Downloads/DyDown
  
  # 日志配置
  logging:
    # 日志等级：DEBUG/INFO/WARNING/ERROR
    level: INFO
    # 单个日志文件最大尺寸
    max_size: 10MB
    # 保留日志文件个数
    backups: 5

# 网络请求配置
network:
  # 请求超时时间（秒）
  timeout: 30
  # 失败重试次数
  retries: 3
  # 代理设置（示例：http://user:pass@host:port）
  proxy: null

# 任务队列配置
task_queue:
  # 最高优先级级别
  max_priority: 10
  # 默认任务优先级
  default_priority: 5
  # 失败任务重试间隔（秒）
  retry_interval: 300
  # 同时进行的优先任务数量
  priority_slots: 2

# 系统托盘配置
tray:
  # 是否显示下载进度百分比
  show_percentage: true
  # 主题颜色（light/dark/system）
  theme: system

