name: Performance Regression Test

on: [push]

jobs:
  performance-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust prometheus-client requests

    - name: Run performance test
      run: |
        python scripts/performance_test.py &
        locust -f scripts/performance_test.py --headless -u 100 -r 10 --run-time 5m

    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: performance-report
        path: |
          performance_stats.csv
          prometheus_metrics.log